drop table if exists bookmarks;

create table bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER 
);

insert into bookmarks (title, url, description, rating)
values
    ('Apple', 'https://www.apple.com', 'All the pretty things', 5),
    ('Google', 'https://www.google.com', 'All the services', 5),
    ('Pokemon', 'https://www.pokemon.com', 'Gotta catch em all', 5),
    ('Amazon', 'https://www.amazon.com', '', 4),
    ('Politico', 'https://www.politico.com', '', 3),
    ('Yahoo', 'https://www.yahoo.com', null, null);